name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: devlog    # Replace with your app service name
  AZURE_WEBAPP_PACKAGE_PATH: './backend/publish'
  DOTNET_VERSION: '9.0.x'      # Your .NET version
  WORKING_DIRECTORY: './backend'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    - name: Publish
      run: dotnet publish BlogApi.API/BlogApi.API.csproj -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 