name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./backend
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./backend
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      working-directory: ./backend
      
    - name: Publish
      if: github.ref == 'refs/heads/main'
      run: dotnet publish --configuration Release --output ./publish
      working-directory: ./backend
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: backend-artifact
        path: backend/publish 